name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "600004804c3fdec28bd61a9c069a09970769a7c8c27d9ee74aae6365b9231a21"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
