name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "334be9c91a3246a3af5391d2e1ba47512d18b9f72552aa01572ac2cfe3255155"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
