name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f71a0867e56e7567b7ae7e4ad7ab226462b91d341e941a22cb0bba281ed29493"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
