name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d059adceac47f5b7d19092670a08364a76a672e6a426425f413afffc6263b8f"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
