name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cebcd0ddb8147a4f7cc4b66584ac4fb8a7f081f1bc3a598632bf05235cbef7c"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
