name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7659d478ca312f7c4a0efbece6162c3663ca879b973e3344cf08698aa258dba"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
