name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b56542ee13af11594088067e70d47f3b9caf50a8f72083d2be80be80c1b27e22"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
