name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceb5c7fd7eb77f8ad377571f0cab4a708934d67528c039cc5312db69cda67089"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
