name = "o3-dev"
author = "Jitter"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6300a7a87bbd7fdce9b4d430a1a1a670a97c31254ab84e29f7da4a230452dbaa"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
